version: '3'

networks:
  nat:
    external: true
  internal:
    external: false

services:
  mosquitto:
#    image: suculent/thinx-message_broker
    build: .
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: on-failure
    env_file: .env
    networks:
      - nat
      - internal
    volumes:
      - /mnt/data/mosquitto/config:/mqtt/config:rw
      - /mnt/data/mosquitto/data:/mqtt/data:rw
      - /mnt/data/mosquitto/log:/mqtt/ssl:rw
      - /mnt/data/mosquitto/ssl:/mqtt/ssl:rw
      - /mnt/data/mosquitto/auth:/mqtt/auth:rw
