version: '3'

networks:
  nat:
    external: true
  internal:
    external: false

services:
  mosquitto:
    user: mosquitto # or ${CURRENT_UID} if CURRENT_UID=$(id -u):$(id -g) docker-compose up
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: on-failure
    env_file: .env
    networks:
      - nat
      - internal
    volumes:
      - /mnt/data/mosquitto/config:/mqtt/config:rw
      - /mnt/data/mosquitto/data:/mqtt/data:rw
      - /mnt/data/mosquitto/ssl:/mqtt/ssl:rw
      - /mnt/data/mosquitto/auth:/mqtt/auth:rw
