version: '3'

networks:
  nat:
    external: true
  internal:
    external: false

services:
  mosquitto:
#    image: suculent/thinx-message_broker
    build: .
    ports:
      - "1883:1883"
      - "8883:8883"
    restart: always
    env_file: .env
    networks:
      - nat
      - internal
    volumes:
      - /mnt/data/mosquitto:/mqtt
